name: Tests
on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]
jobs:
  size:
    runs-on: ${{ matrix.os }}
    strategy:
       matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node_version:
          - 14
          - 16
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 7.1.2
      - run: pnpm install
      - run: pnpm test