name: Tests
on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
       matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node_version:
          - 14
          - 16
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4.0.0
        with:
          version: 7.x
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
      - run: pnpm install --frozen-lockfile
      - run: pnpm test
  test-status:
    runs-on: ubuntu-22.04
    needs: [test]
    if: ${{ always() }}
    steps:
      - name: Successful deploy
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: Failing deploy
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1